### ISSUE TITLE
[spike] investigate persistent data storage

### ISSUE THREAD

**Issue by TheSophia22** [Ukraine-Relief-Efforts/ukraine#115]
For these three tickets:
- Donation Comments
- Evidence Upload
- Request Evidence

We need a data storage solution. Should be easy to upload to, read, and render data. It should also be able to read from the spreadsheet.

Legacy comments: 
roseja: In addition, Contentful allows for localized content, so this could be a better way to handle translations in the future. It will take some time to set up the schema to implement this though.

Birdman: I would like to see us use Contentful along with GraphQL API. Lots of examples out there for NextJS apps and Vercel has integration with Contentful.

The cool thing about Contentful is that we could create an Org Content profile in place of Google Sheets. There we could have Content managers add or edit content without needing Devs. In our app we could query the Org Content profile using GraphQL.

[Next.js and Contentful with Lee Robinson from Vercel](https://www.youtube.com/watch?v=bMRQgguzBLs)[](https://github.com/moxystudio/react-contentful-image)[](https://github.com/moxystudio/react-contentful-image)

[GitHub - moxystudio/react-contentful-image: A react image renderer that uses the Contentful Images API.](https://github.com/moxystudio/react-contentful-image)[](https://github.com/yellowme/contentful-next)[](https://github.com/yellowme/contentful-next)

[GitHub - yellowme/contentful-next: A simple Next.js site powered by Contentful and ready for deployment on Vercel](https://github.com/yellowme/contentful-next)[](https://github.com/contentful-labs/file-upload-example)[](https://github.com/contentful-labs/file-upload-example)

[GitHub - contentful-labs/file-upload-example: Example application to demonstrate the new direct file upload feature of Contentful.](https://github.com/contentful-labs/file-upload-example)

**Comment by shenanigansd** [comment]
Closed in favor of #156
