### ISSUE TITLE
Create "Fundraiser" content type in Contenful

### ISSUE THREAD

**Issue by shenanigansd** [Ukraine-Relief-Efforts/ukraine#155]
A new "Fundraiser" `content model` will need to be created in Contentful to store fundraiser data.
This issue serves to track changes to the `content model` and to provide a master list of new database column names.

**Comment by shenanigansd** [comment]
| Old field name                       | Contentful name                    | Contentful slug               | Contentful Type  |
|--------------------------------------|------------------------------------|-------------------------------|------------------|
| Organization Name                    | Organization Name                  | organizationName              | Short text       |
| Donation Link                        | Donation Link                      | donationLink                  | Short text       |
| Contact for Large Donations          | Contact for Large Donations        | contactForLargeDonations      | Rich Text        |
| Description (English)                | Description                        | description                   | Rich Text        |
| Cause                                | Cause                              | cause                         | Short text, list |
| How will they spend donations        | How will they spend donations      | howWillTheySpendDonations     | Rich text        |
| What they have accomplished so far   | What they have accomplished so far | whatTheyHaveAccomplishedSoFar | Short text       |
| Institutional backing                | Institutional backing              | institutionalBacking          | Rich Text        |
| Payment method                       | Payment method                     | paymentMethod                 | Rich Text        |
| Crypto supported?                    | Supports Cryptocurrency?           | supportsCryptocurrency        | Boolean          |
| Instagram                            | Instagram                          | instagram                     | Short text       |
| Facebook                             | Facebook                           | facebook                      | Short text       |
| Twitter                              | Twitter                            | twitter                       | Short text       |
| Organization Website                 | Organization Website               | organizationWebsite           | Short text       |
| Banner Image                         | Banner Image                       | bannerImage                   | Media            |
| Small Org?                           | Small organization?                | smallOrganization             | Boolean          |
| Banner Image                         |||
| Additional What we have accomplished | What we have accomplished          | whatWeHaveAccomplished        | Rich Text        |
| URL name                             | Slug                               | slug                          | Short Text       |
| Longer description                   | Description 2                      | description2                  | Rich Text        |

**Comment by roseja** [comment]
@shenanigansd I'm working on https://github.com/Ukraine-Relief-Efforts/ukraine/issues/156. Is it possible for me to get access to Contentful to review the schema? If accounts are limited at this time I understand as well and will continue to update what I can without direct access.

**Comment by shenanigansd** [comment]
@roseja , unfortunately, yeah, accounts are limited at this time.
What're you needing to review?
If you're wanting to test, I can create you an API token for the GrahiQL Playground?

**Comment by shenanigansd** [comment]
Data model is no longer being tracked by this issue.
